use_frameworks!
# inhibit_all_warnings!

target 'RCCards_Example' do
	platform :ios, '10.0'
	
	pod 'RCCards', :path => '../'

	target 'RCCards_Tests' do
		inhibit_all_warnings!
		# inherit! :search_paths

		pod 'Quick', '~> 1.0'
		pod 'Nimble', '~> 7.0'
		pod 'FBSnapshotTestCase' , '~> 2.0'
		pod 'Nimble-Snapshots' , '~> 6.0'
	end

	post_install do |installer|
	    installer.pods_project.targets.each do |target|
	        case target.name 
		        when 'Quick', 'Nimble', 'FBSnapshotTestCase', 'Nimble-Snapshots'
		            target.build_configurations.each do |config|
		                config.build_settings['SWIFT_VERSION'] = '4.0'
		            end
		        end
	    end
	end
end

